config/routes.rb
Rails.application.routes.draw do
  resources :members
  
  

  root 'welcome#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
	searchkick  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    if params[:query].present?
      @member = Member.search(params[:query], page: params[:page])
    else
      @member = Member.all
    end
  end
  
  def new
  end

  def edit
    @member = Member.find(params[:id])
  end

  def show
    @member = Member.find(params[:id])
  end
  
  def create
    @member = Member.new(member_params)
    @member.save
    redirect_to @member
  end

  def update
    @member = Member.find(params[:id])

    if @member.update(member_params)
      redirect_to @member
    else
      render 'edit'
    end
  end
  
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    redirect_to members_path
  end

  private
  def member_params
    params.require(:member).permit(:first_name,:last_name,:email,:status)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PricingApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/members/edit.html.erb
<h1>Editing Member Info</h1>

<%= form_for :member, url: member_path(@member), method: :patch do |f| %>

<% if @member.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@member.errors.count, "error") %> prohibited
    this article from being saved:
  </h2>
  <ul>
    <% @member.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<p>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
</p>

<p>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
</p>

<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.label :status %><br>
  <%= f.radio_button :status, 'R', :checked => true %>
  <%= label :status_R, 'R' %><br>
  <%= f.radio_button :status, 'V', :checked => false %>
  <%= label :status_V, 'V' %><br>
  <%= f.radio_button :status, 'SV', :checked => false %>
  <%= label :status_SV, 'SV' %><br>
  <%= f.radio_button :status, 'FS', :checked => false %>
  <%= label :status_FS, 'FS' %><br>
  <%= f.radio_button :status, 'S', :checked => false %>
  <%= label :status_S, 'S' %><br>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

<%= link_to 'See member list', members_path %>

app/views/members/index.html.erb
<h1>Listing Members</h1>

<table>
  <tr>
    <th>first</th>
    <th>last</th>
    <th>email</th>
    <th>status</th>
  </tr>

  <% @member.each do |member| %>
  <tr>
    <td><%= member.first_name %></td>
    <td><%= member.last_name %></td>
    <td><%= member.email %></td>
    <td><%= member.status %></td>
    <td><%= link_to 'Show', member_path(member) %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member_path(member),
	    method: :delete,
	    data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>
<br>

<%= link_to "Back to Home", root_path  %><br>
<%= link_to "New member", new_member_path  %>

app/views/members/new.html.erb
<h1>New Member </h1>
<%= form_for :member, url: members_path do |f| %>
<p>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
</p>

<p>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
</p>

<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.label :status %><br>
  <%= f.radio_button :status, 'R', :checked => true %>
  <%= label :status_R, 'R' %><br>
  <%= f.radio_button :status, 'V', :checked => false %>
  <%= label :status_V, 'V' %><br>
  <%= f.radio_button :status, 'SV', :checked => false %>
  <%= label :status_SV, 'SV' %><br>
  <%= f.radio_button :status, 'FS', :checked => false %>
  <%= label :status_FS, 'FS' %><br>
  <%= f.radio_button :status, 'S', :checked => false %>
  <%= label :status_S, 'S' %><br>
</p>


<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to 'See member list', members_path %>

app/views/members/show.html.erb
<p>
  <strong>First: </strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last: </strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>email: </strong>
  <%= @member.email %>
</p>

<p>
  <strong>Status: </strong>
  <%= @member.status %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %><br>
<%= link_to 'Back', members_path %>

app/views/welcome/index.html.erb
<p>Welcome to the Caltech Tango Club attenance organization tool</p><br>

<%= link_to 'See member list', controller: 'members' %><br>
<%= link_to 'New member', new_member_path %>